# Generated by Django 3.2.4 on 2021-07-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.CharField(max_length=30, verbose_name='證券代號')),
                ('date', models.DateField(verbose_name='日期')),
                ('stock_name', models.CharField(max_length=30, verbose_name='證券名稱')),
                ('open', models.IntegerField(verbose_name='開盤價')),
                ('high', models.IntegerField(verbose_name='最高點')),
                ('low', models.IntegerField(verbose_name='最低點')),
                ('Increase', models.IntegerField(verbose_name='當日漲幅')),
                ('close', models.IntegerField(verbose_name='收盤價')),
                ('buy', models.CharField(blank=True, max_length=30, null=True, verbose_name='第二天買入價格')),
                ('self', models.CharField(blank=True, max_length=30, null=True, verbose_name='第三天賣出價格')),
            ],
            options={
                'verbose_name': '股票',
                'verbose_name_plural': '股票',
            },
        ),
    ]
