# Generated by Django 3.2.4 on 2021-07-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='date',
            new_name='stock_date',
        ),
        migrations.AlterField(
            model_name='stock',
            name='Increase',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='當日漲幅'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='buy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='第二天買入價格'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='close',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='收盤價'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='high',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='最高點'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='low',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='最低點'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='open',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='開盤價'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='self',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='第三天賣出價格'),
        ),
    ]
