# Generated by Django 3.2.4 on 2021-07-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20210706_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_date',
            field=models.CharField(max_length=30, verbose_name='日期'),
        ),
    ]
