# Generated by Django 3.2.4 on 2021-07-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_stock_stock_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='buy',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='第二天買入價格'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='self',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='第三天賣出價格'),
        ),
    ]
