# Generated by Django 3.2.4 on 2021-07-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20210706_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='buy_date',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='買超日期'),
        ),
    ]
