# Generated by Django 3.2.4 on 2021-07-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='陳昜睿', max_length=30, verbose_name='姓名')),
                ('introduction', models.TextField(max_length=1000, verbose_name='自我介紹')),
                ('photo', models.ImageField(blank=True, upload_to='static/assets/img', verbose_name='大頭貼')),
                ('mail', models.CharField(max_length=100, verbose_name='電子信箱')),
                ('phone', models.CharField(max_length=100, verbose_name='手機')),
                ('address', models.CharField(max_length=100, verbose_name='地址')),
                ('twitterid', models.CharField(max_length=100, verbose_name='推特ID')),
                ('fbid', models.CharField(max_length=100, verbose_name='臉書ID')),
                ('igid', models.CharField(max_length=100, verbose_name='IG')),
                ('githubid', models.CharField(max_length=100, verbose_name='github')),
            ],
            options={
                'verbose_name': '使用者資料',
                'verbose_name_plural': '使用者資料',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=100, verbose_name='公司名稱')),
                ('position', models.CharField(max_length=50, verbose_name='職位')),
                ('content', models.TextField(max_length=600, verbose_name='工作內容')),
                ('start', models.DateField(verbose_name='工作時間起')),
                ('end', models.DateField(blank=True, null=True, verbose_name='工作時間迄')),
            ],
            options={
                'verbose_name': '工作經驗',
                'verbose_name_plural': '工作經驗',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='標題')),
                ('content', models.TextField(max_length=200, verbose_name='內容')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
    ]
