# Generated by Django 3.2.4 on 2021-07-01 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awardname', models.CharField(max_length=50, verbose_name='獎項與名稱')),
                ('awarddate', models.DateField(blank=True, null=True, verbose_name='獲獎日')),
            ],
            options={
                'verbose_name': '獎項與名稱',
                'verbose_name_plural': '獎項與名稱',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=50, verbose_name='學校名稱')),
                ('department', models.CharField(max_length=50, verbose_name='科系名稱')),
                ('status', models.CharField(max_length=50, verbose_name='就學狀態')),
                ('duringstart', models.DateField(verbose_name='開始時間')),
                ('duringsend', models.DateField(blank=True, null=True, verbose_name='畢業時間')),
            ],
            options={
                'verbose_name': '學歷',
                'verbose_name_plural': '學歷',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=50, verbose_name='專案名稱')),
                ('projectstart', models.DateField(verbose_name='開始時間')),
                ('projectend', models.DateField(blank=True, null=True, verbose_name='結束時間')),
                ('projectcontent', models.TextField(max_length=600, verbose_name='專案描述')),
                ('projecturl', models.URLField(blank=True, verbose_name='專案連結')),
                ('projectimg', models.ImageField(blank=True, upload_to='static/assets/img', verbose_name='專案圖片')),
            ],
            options={
                'verbose_name': '專案成就',
                'verbose_name_plural': '專案成就',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillname', models.CharField(max_length=50, verbose_name='專長名稱')),
                ('skillcontect', models.TextField(max_length=600, verbose_name='專長描述')),
                ('skilltag', models.CharField(max_length=200, verbose_name='專長標籤')),
            ],
            options={
                'verbose_name': '專長',
                'verbose_name_plural': '專長',
            },
        ),
        migrations.AddField(
            model_name='about',
            name='interests',
            field=models.TextField(default='something', max_length=600, verbose_name='興趣'),
        ),
    ]
