# Generated by Django 4.1.2 on 2022-10-21 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camera',
            options={'verbose_name': '攝影機', 'verbose_name_plural': '攝影機'},
        ),
        migrations.RemoveField(
            model_name='camera',
            name='my_field_name',
        ),
        migrations.AddField(
            model_name='camera',
            name='title',
            field=models.CharField(default='test', max_length=20, verbose_name='標題'),
        ),
    ]
