# Generated by Django 4.1.2 on 2022-10-21 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_alter_camera_options_remove_camera_my_field_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='camera_id',
            field=models.CharField(default='0', max_length=100, verbose_name='網路攝影機'),
        ),
    ]
