# Generated by Django 4.1.2 on 2022-10-21 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0003_camera_camera_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='camera_id',
            field=models.TextField(default='0', max_length=100, verbose_name='網路攝影機'),
        ),
    ]
