# Generated by Django 4.1.2 on 2022-10-24 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0004_alter_camera_camera_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='camera_url',
            field=models.TextField(blank=True, default='0', max_length=100, verbose_name='攝影機位置'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='camera_id',
            field=models.TextField(blank=True, max_length=100, unique=True, verbose_name='攝影機編號'),
        ),
    ]
