# Generated by Django 4.1.2 on 2022-10-24 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0005_camera_camera_url_alter_camera_camera_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='dday',
            field=models.IntegerField(blank=True, default=1, verbose_name='固定刪除檔案時間(天數)'),
        ),
        migrations.AddField(
            model_name='camera',
            name='fast',
            field=models.IntegerField(blank=True, default=25, verbose_name='移動偵測靈敏度'),
        ),
        migrations.AddField(
            model_name='camera',
            name='mailCheck',
            field=models.BooleanField(default=True, verbose_name='是否移動發信'),
        ),
        migrations.AddField(
            model_name='camera',
            name='moveNotice',
            field=models.IntegerField(blank=True, default=60, verbose_name='移動偵測通知時間(秒數)'),
        ),
        migrations.AddField(
            model_name='camera',
            name='scancheck',
            field=models.BooleanField(default=True, verbose_name='是否移動截圖'),
        ),
    ]
