# Generated by Django 4.1.2 on 2022-10-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0006_camera_dday_camera_fast_camera_mailcheck_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='fps',
            field=models.IntegerField(blank=True, default=30, verbose_name='預設幀數'),
        ),
        migrations.AddField(
            model_name='camera',
            name='heigth',
            field=models.IntegerField(blank=True, default=1280, verbose_name='螢幕高度'),
        ),
        migrations.AddField(
            model_name='camera',
            name='width',
            field=models.IntegerField(blank=True, default=1280, verbose_name='螢幕寬度'),
        ),
    ]
