# Generated by Django 4.1.2 on 2022-10-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0008_camera_cameradisplay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='cameraDisplay',
        ),
        migrations.AddField(
            model_name='camera',
            name='isOpened',
            field=models.BooleanField(default=True, verbose_name='是否啟動'),
        ),
    ]
