# Generated by Django 4.1.2 on 2022-10-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0009_remove_camera_cameradisplay_camera_isopened'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='heigth',
            field=models.IntegerField(blank=True, default=720, verbose_name='螢幕高度'),
        ),
    ]
