# Generated by Django 3.1.3 on 2022-10-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0010_alter_camera_heigth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
