# Generated by Django 3.1.3 on 2022-10-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0011_auto_20221024_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.TextField(blank=True, max_length=100, unique=True, verbose_name='攝影機編號')),
                ('movetime', models.DateField(blank=True, verbose_name='移動時間')),
                ('photo', models.ImageField(blank=True, upload_to='static/my_output', verbose_name='移動截圖')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='新增時間')),
            ],
            options={
                'verbose_name': '移動偵測',
                'verbose_name_plural': '移動偵測',
            },
        ),
    ]
