# Generated by Django 3.1.3 on 2022-10-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0012_move'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='camera_id',
            field=models.TextField(blank=True, max_length=100, verbose_name='攝影機編號'),
        ),
        migrations.AlterField(
            model_name='move',
            name='movetime',
            field=models.DateTimeField(auto_now=True, verbose_name='移動時間'),
        ),
        migrations.AlterField(
            model_name='move',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/my_output', verbose_name='移動截圖'),
        ),
    ]
