# Generated by Django 3.2.16 on 2022-10-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0014_auto_20221028_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='videocheck',
            field=models.BooleanField(default=True, verbose_name='是否連續錄製'),
        ),
        migrations.AddField(
            model_name='camera',
            name='videodday',
            field=models.IntegerField(blank=True, default=3, verbose_name='固定刪除影片檔案時間(天數)'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='dday',
            field=models.IntegerField(blank=True, default=7, verbose_name='固定刪除截圖檔案時間(天數)'),
        ),
    ]
