# Generated by Django 3.2.16 on 2022-11-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0016_move_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='mailCheck',
            field=models.BooleanField(default=False, verbose_name='是否移動發信'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='scancheck',
            field=models.BooleanField(default=False, verbose_name='是否移動截圖'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='videocheck',
            field=models.BooleanField(default=False, verbose_name='是否連續錄製'),
        ),
    ]
