# Generated by Django 3.2.16 on 2022-11-02 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0017_auto_20221101_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='move',
            name='camera_id',
        ),
        migrations.AddField(
            model_name='move',
            name='camera',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='move', to='camera.camera'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField(blank=True, null=True, verbose_name='影片起時')),
                ('endtime', models.DateTimeField(blank=True, null=True, verbose_name='影片迄時')),
                ('movie', models.TextField(blank=True, max_length=200, null=True, unique=True, verbose_name='影片位置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='新增時間')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='camera.camera')),
            ],
            options={
                'verbose_name': '影片管理',
                'verbose_name_plural': '影片管理',
            },
        ),
    ]
