# Generated by Django 3.2.16 on 2022-11-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0018_auto_20221102_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='recordspeed',
            field=models.FloatField(blank=True, default=6.0, null=True, verbose_name='錄製倍率'),
        ),
    ]
