# Generated by Django 3.2.16 on 2022-11-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomname', models.TextField(blank=True, max_length=20, verbose_name='聊天室')),
                ('nickname', models.TextField(blank=True, max_length=20, verbose_name='暱稱')),
                ('message', models.CharField(blank=True, max_length=200, verbose_name='說話內容')),
                ('isdisable', models.BooleanField(default=True, verbose_name='是否可被看見')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='新增時間')),
            ],
            options={
                'verbose_name': '聊天紀錄',
                'verbose_name_plural': '聊天紀錄',
            },
        ),
    ]
