# Generated by Django 3.2.4 on 2021-06-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.CharField(max_length=400, verbose_name='自我介紹')),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='大頭貼')),
                ('mail', models.CharField(max_length=100, verbose_name='電子信箱')),
                ('phone', models.CharField(max_length=100, verbose_name='手機')),
                ('address', models.CharField(max_length=100, verbose_name='地址')),
                ('twitterid', models.CharField(max_length=100, verbose_name='推特ID')),
                ('fbid', models.CharField(max_length=100, verbose_name='臉書ID')),
                ('igid', models.CharField(max_length=100, verbose_name='IG')),
                ('githubid', models.CharField(max_length=100, verbose_name='github')),
            ],
            options={
                'verbose_name': '使用者資料',
                'verbose_name_plural': '使用者資料',
            },
        ),
    ]
