# Generated by Django 3.2.4 on 2021-06-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='name',
            field=models.CharField(default='陳昜睿', max_length=30, verbose_name='姓名'),
        ),
    ]
