# Generated by Django 3.2.4 on 2021-06-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=100, verbose_name='公司名稱')),
                ('position', models.CharField(max_length=50, verbose_name='職位')),
                ('content', models.CharField(max_length=600, verbose_name='工作內容')),
                ('start', models.DateField(auto_now_add=True, verbose_name='工作時間起')),
                ('end', models.DateField(auto_now_add=True, verbose_name='工作時間迄')),
                ('url', models.URLField(blank=True, verbose_name='demo網站')),
            ],
            options={
                'verbose_name': '工作經驗',
                'verbose_name_plural': '工作經驗',
            },
        ),
    ]
